### PR TITLE
[DEVOPS-524] Add netboot image to CI pipeline

### PR DESCRIPTION
**Pull request by Jasper-Ben**

### CODE REVIEW

**Review by linkjumper — APPROVED** [review]
Tested!

**Comment by ThomasWNoack** [comment]
Gitlab-CI is green

**Review by ThomasWNoack — APPROVED** [review]
lgtm

**Comment by ThomasWNoack** [comment]
## Maintainer Checklist
- Is there a changelog entry? *Yes*
- Do the commit messages comply with the specifications? *Yes*
- Was a Jenkins run performed and was it error-free? *Yes*
- Is a manual rebase necessary? *no*

**Pull request merged**
