### PR TITLE
[RDPHOEN-1067] Add r2 build to Jenkins CI

### PR DESCRIPTION
**Pull request by Jasper-Ben**

### CODE REVIEW

**Review by DanielBaumgart — APPROVED** [review]

**Review by martin31821 — APPROVED** [review]

**Comment by Jasper-Ben** [comment]
Requires that the r2 multiconf is named `kas-irma6-imx8mp-irma6r2.yml`. Requires renaming and adjustments to Makefile.

**Comment by ThomasWNoack** [comment]
Please add a changelog entry and do a Jenkins run on the intranet (and link the pipeline number here).

**Comment by Jasper-Ben** [comment]
> do a Jenkins run on the intranet (and link the pipeline number here).

This does not affect the legacy Jenkins in any way. Files changed are irrelevant for the old CI.

**Comment by Jasper-Ben** [comment]
> Requires that the r2 multiconf is named `kas-irma6-imx8mp-irma6r2.yml`. Requires renaming and adjustments to Makefile.

done.

**Pull request merged**
